export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAILURE = 'SUBMIT_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const GET_STUDENT_DATA_SUCCESS = 'GET_STUDENT_DATA_SUCCESS';
export const GET_STUDENT_DATA_FAILURE = 'GET_STUDENT_DATA_FAILURE';

export const RESET = 'RESET' 